/**
 * Blueprint generation.
 *
 * This is the factory's only write path to Render. Nothing here calls an API:
 * it produces YAML, the workflow commits it, and Render's Blueprint sync
 * creates and deploys whatever changed. That means every piece of
 * infrastructure the factory has ever created is reviewable in Git, and an
 * agent cannot provision anything without a commit.
 *
 * Blueprints are generated from the agent-declared service manifest, not from
 * constants. The manifest is what the builder says it built: directories,
 * commands, health paths, env var wiring.
 */
import { airoConfig, appRelativePath } from "../airo.config.js";
import type { AppSpec, Manifest, Service } from "./contracts.js";

export interface ResourceNames {
	web: string;
	api: string | null;
	db: string | null;
}

/**
 * Render resource names are unique per workspace, and the root Blueprint holds
 * every generated app at once, so the user and app names both have to be in
 * here. Components are truncated to keep the whole name within Render's limit.
 */
export function resourceNames(spec: AppSpec): ResourceNames {
	const stem = [
		airoConfig.resourcePrefix,
		spec.user.slice(0, 12),
		spec.appName.slice(0, 24),
	].join("-");

	const hasApi = spec.manifest.services.some((s) => s.kind === "web_service");
	const hasDb = (spec.manifest.databases ?? []).length > 0;

	return {
		web: `${stem}-web`,
		api: hasApi ? `${stem}-api` : null,
		db: hasDb ? `${stem}-db` : null,
	};
}

/**
 * The Blueprint for one app, committed beside it. Deployable on its own by
 * pointing a new Blueprint at this path, which is how a generated app can
 * graduate out of the factory's shared Blueprint.
 */
export function appBlueprint(spec: AppSpec): string {
	const root = appRelativePath(spec.user, spec.appName);
	const names = resourceNames(spec);
	return [
		`# ${spec.user}/${spec.appName} — generated by the Airo factory.`,
		`# Prompt: ${oneLine(spec.prompt)}`,
		"",
		"services:",
		...serviceBlocks(spec.manifest, root, names),
		...databaseBlocks(spec.manifest, names),
	].join("\n");
}

/**
 * The repository-root Blueprint: every generated app in one file. This is the
 * file Render watches, so appending an app to it is what deploys that app.
 * Regenerated from every apps/<user>/<app>/airo.json on each run, which is why
 * the specs are stored as JSON rather than parsed back out of YAML.
 */
export function rootBlueprint(specs: readonly AppSpec[]): string {
	const ordered = [...specs].sort((a, b) =>
		`${a.user}/${a.appName}`.localeCompare(`${b.user}/${b.appName}`),
	);

	const header = [
		"# Generated by the Airo factory. Do not edit by hand.",
		"#",
		"# One Blueprint holds every app the factory has built. A run appends its",
		"# app's resources here, and Render's Blueprint sync deploys them.",
		`# Apps: ${ordered.length}`,
		"",
	];

	if (ordered.length === 0) {
		return [
			...header,
			"# No apps yet. The first run will add one.",
			"services: []",
			"",
		].join("\n");
	}

	const services: string[] = [];
	const databases: string[] = [];
	for (const spec of ordered) {
		const root = appRelativePath(spec.user, spec.appName);
		const names = resourceNames(spec);
		services.push(`  # ── ${spec.user}/${spec.appName} ${"─".repeat(20)}`);
		services.push(...serviceBlocks(spec.manifest, root, names));
		databases.push(...databaseBlocks(spec.manifest, names).slice(1));
	}

	return [
		...header,
		"services:",
		...services,
		...(databases.length > 0 ? ["databases:", ...databases] : []),
		"",
	].join("\n");
}

/* ── YAML generation from manifest ────────────────────────────────────── */

function serviceBlocks(
	manifest: Manifest,
	root: string,
	names: ResourceNames,
): string[] {
	const lines: string[] = [];

	for (const service of manifest.services) {
		const resourceName = resolveServiceName(service, names);
		lines.push(...singleServiceBlock(service, root, resourceName, names));
	}

	return lines;
}

function resolveServiceName(service: Service, names: ResourceNames): string {
	if (service.kind === "web_service" && names.api) return names.api;
	return names.web;
}

function singleServiceBlock(
	service: Service,
	root: string,
	resourceName: string,
	names: ResourceNames,
): string[] {
	const lines: string[] = [];
	const isStatic = service.kind === "static_site";

	// Normalize rootDir: "." means the app root itself, not a subdirectory.
	const serviceDir =
		service.rootDir === "." ? root : `${root}/${service.rootDir}`;

	lines.push(
		"  - type: web",
		`    name: ${resourceName}`,
		`    runtime: ${isStatic ? "static" : service.runtime}`,
	);
	// Static sites are served from the global CDN — no region field.
	if (!isStatic) {
		lines.push(`    plan: ${airoConfig.render.servicePlan}`);
		lines.push(`    region: ${airoConfig.render.region}`);
	}
	lines.push(
		`    rootDir: ${serviceDir}`,
		`    buildCommand: ${service.buildCommand}`,
	);

	if (!isStatic && service.startCommand) {
		lines.push(`    startCommand: ${service.startCommand}`);
	}
	if (isStatic && service.staticPublishPath) {
		lines.push(`    staticPublishPath: ${service.staticPublishPath}`);
	}
	if (!isStatic && service.healthCheckPath) {
		lines.push(`    healthCheckPath: ${service.healthCheckPath}`);
	}

	lines.push(
		"    autoDeployTrigger: commit",
		"    buildFilter:",
		"      paths:",
		`        - ${serviceDir}/**`,
	);

	const envVars = service.envVars ?? [];
	// Wire env vars declared by the manifest.
	const envLines: string[] = [];
	for (const envVar of envVars) {
		envLines.push(`      - key: ${envVar.key}`);
		if (envVar.fromDatabase && names.db) {
			envLines.push(
				"        fromDatabase:",
				`          name: ${names.db}`,
				`          property: ${envVar.fromDatabase.property}`,
			);
		} else if (envVar.fromService) {
			const targetName = resolveFromServiceName(envVar.fromService.name, names);
			envLines.push(
				"        fromService:",
				`          name: ${targetName}`,
				"          type: web",
				`          property: ${envVar.fromService.property}`,
			);
		}
	}
	if (envLines.length > 0) {
		lines.push("    envVars:", ...envLines);
	}

	return lines;
}

/**
 * Resolve a logical service reference (like "api" or "web") from the manifest
 * into the actual Render resource name.
 */
function resolveFromServiceName(
	logicalName: string,
	names: ResourceNames,
): string {
	if (logicalName === "api" && names.api) return names.api;
	if (logicalName === "web") return names.web;
	if (logicalName === "db" && names.db) return names.db;
	// Fall back to the web resource.
	return names.api ?? names.web;
}

function databaseBlocks(manifest: Manifest, names: ResourceNames): string[] {
	if (!names.db || !manifest.databases?.length) return [];
	return [
		"databases:",
		`  - name: ${names.db}`,
		`    plan: ${airoConfig.render.databasePlan}`,
		`    region: ${airoConfig.render.region}`,
		`    postgresMajorVersion: "${airoConfig.render.postgresMajorVersion}"`,
		"    ipAllowList: []",
	];
}

function oneLine(value: string): string {
	return value.replace(/\s+/g, " ").slice(0, 160);
}
